[book]
authors = ["lovingzizi"]
language = "en"
multilingual = false
src = "src"
title = "ZK SHANGHAI"

[output.html]
mathjax-support = true
site-url = "https://zkshanghai.xyz"
git-repository-url = "https://github.com/dicaprioJ/zkshanghai-workshop"

[output.html.playground]
editable = true
line-numbers = true

[output.html.search]
limit-results = 20
use-boolean-and = true
boost-title = 2
boost-hierarchy = 2
boost-paragraph = 1
expand = true
heading-split-level = 2